---
title: "Model"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse) # general
library(ggalt) # dumbbell plots
library(countrycode) # continent
library(rworldmap) # quick country-level heat maps
library(gridExtra) # plots
library(broom) # significant trends within countries
theme_set(theme_light())
library(plyr)
library(dplyr)
library(lubridate)
library(caTools)
library(ggplot2)
library(ggthemes)
library(reshape2)
library(data.table)
library(tidyr)
library(corrgram)       
library(corrplot)
library(formattable)
library(cowplot)
library(ggpubr)
library(plot3D)
```

```{r, message=FALSE, warning=FALSE}
## clean the data
data <- read_csv("./data/master.csv") %>% 
  janitor::clean_names()
survey <- read_csv("./data/survey.csv") %>% 
  janitor::clean_names()
happiness_2015 <- read_csv("./data/2015.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    year = 2015
  ) %>% 
  select(-region, -standard_error)
happiness_2016 <- read_csv("./data/2016.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    year = 2016
  ) %>% 
  select(-region, -lower_confidence_interval, -upper_confidence_interval)
happiness_2017 <- read_csv("./data/2017.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    year = 2017
  ) %>% 
  select(-whisker_high, -whisker_low) 

happiness_2015 = happiness_2015[, c(1,11,2,3,4,5,6,7,8,9,10)]
happiness_2016 = happiness_2016[, c(1,11,2,3,4,5,6,7,8,9,10)]
happiness_2017 = happiness_2017[, c(1,11,2,3,4,5,6,7,9,8,10)]
happiness = rbind(happiness_2015, happiness_2016, happiness_2017)

## generate correlation plot
Num.cols <- sapply(happiness, is.numeric)
Cor.data <- cor(happiness[, Num.cols])

corrplot(Cor.data, method = 'color') 
```


